# Generated by Django 3.1.2 on 2020-11-11 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='locationImage',
            field=models.ImageField(blank=True, upload_to='images/locations/'),
        ),
        migrations.AlterField(
            model_name='author_book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.author'),
        ),
        migrations.AlterField(
            model_name='author_book',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.book'),
        ),
        migrations.AlterField(
            model_name='location_book',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.book'),
        ),
        migrations.AlterField(
            model_name='location_book',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.location'),
        ),
    ]
