# Generated by Django 3.1.2 on 2020-11-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201111_0234'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'publicationDate'), name='unique title and date'),
        ),
        migrations.AlterModelTable(
            name='book',
            table='pages_book',
        ),
    ]
