# Generated by Django 3.1.2 on 2020-10-21 03:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201021_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(through='pages.Author_Book', to='pages.Book'),
        ),
        migrations.CreateModel(
            name='Location_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.book')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='books',
            field=models.ManyToManyField(through='pages.Location_Book', to='pages.Book'),
        ),
    ]
