# Generated by Django 3.1.2 on 2020-11-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201115_0416'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('lastName', 'firstName'), name='unique last and first name'),
        ),
        migrations.AlterModelTable(
            name='author',
            table='pages_author',
        ),
    ]
