# Generated by Django 3.1.2 on 2020-12-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201115_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='author_books', through='pages.Author_Book', to='pages.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='book_authors', through='pages.Author_Book', to='pages.Book'),
        ),
    ]
